#!/bin/bash

# ? alternative to `apt-key add`;
# ? arguments:
# ?  - url link to `*.gpg.key` file;
# ?  - output filename at `/usr/share/keyrings/` folder;

if [ $# -ne 2 ] ; then echo -e "\033[0;33m requires two arguments: link to key and output filename \033[0m"; exit 1; fi

#** see https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
wget -O- $1 | gpg --dearmor | sudo tee /usr/share/keyrings/$2 >> /dev/null && exit 0
