--[[
    # ? Mine Conky by allan_walpy [allanwalpy@gmail.com] and tested on Termux on android December 2020 and tested on Archlinux xfce [arm]
]]

conky.config = {
    out_to_ncurses = true,
    out_to_x = false,
    out_to_wayland = false,

    console_graph_ticks = " ,_,=,#",

    total_run_times = 0,

    forced_redraw = false,
    extra_newline = false,

    default_color = "#ffffff",
    color1 = "#88aaff",
    color2 = "#44ff88",
    color3 = "#ee6633",
    color4 = "#ff1111",
    color5 = "#44ff88",
    color6 = "#4488aa",
    color7 = "#33aa66",
    color8 = "#ff8844",
    color9 = "#ff1111",
    color0 = "#333333",
    default_outline_color = "#ffffff",
    default_shade_color = "#ffffff",

    update_interval = 1.0,
    cpu_avg_samples = 2,
    diskio_avg_samples = 2,
    net_avg_samples = 2,
    
    disable_auto_reload = false,

    text_buffer_size = 256,
    override_utf8_locale = true,
    no_buffers = true,
    if_up_strictness = "address",
    format_human_readable = true,
    short_units = false,
    pad_percents = 0,
    use_spacer = "none",
    temperature_unit = "celsius",
    
    default_graph_height = 32,
    default_graph_width = 127,
    default_gauge_height = 32,
    default_gauge_width = 127,

    template0 = "",
}

conky.text = [[
${no_update ${distribution} ${machine} [${nodename}] ${sysname} ${kernel}}
${no_update conky ${conky_build_arch} v${conky_version}}
${no_update ${password 32}}
${time} [${uptime}]

CPU
${cpu cpu0}% ${goto 5}${freq_g cpu0}Ghz ${goto 15}
${cpu cpu1}% ${goto 5}${cpu cpu2}% ${goto 10}${cpu cpu3}%${goto 15}${cpu cpu4}% ${goto 20}${cpu cpu5}% ${goto 25}${cpu cpu6}% ${goto 30}${cpu cpu7}% ${goto 35}${cpu cpu8}% ${goto 40}${cpu cpu9}% ${goto 45}${cpu cpu10}% ${goto 50}${cpu cpu11}% ${goto 55}${cpu cpu12}%
${freq_g cpu1} ${goto 5}${freq_g cpu2} ${goto 10}${freq_g cpu3} ${goto 15}${freq_g cpu4} ${goto 20}${freq_g cpu5} ${goto 25}${freq_g cpu6} ${goto 30}${freq_g cpu7} ${goto 35}${freq_g cpu8} ${goto 40}${freq_g cpu9} ${goto 45}${freq_g cpu10} ${goto 50}${freq_g cpu11} ${goto 55}${freq_g cpu12}
${processes}: ${running_processes} ${threads}: ${running_threads} ${loadavg 1}/${loadavg 2}/${loadavg 3}
${top cpu 1}% ${goto 9}${top name 1} ${goto 22}${top pid 1} ${goto 32}top_time
.
RAM
${shmem} shared; ${memperc}% in use; ${memmax} max; ${mem} mem; ${memavail} avail; ${memdirty} dirty; ${memeasyfree} free easy; ${memfree} free; ${buffers} buffer; ${cached} cached; ${free_bufcache} free bufcache; ${free_cached} free cached; 
${swap} swap; ${swapfree} free; ${swapmax} max; ${swapperc} per; top_mem
.
DISK
${diskio_read /dev/nvme0n1} ${goto 6}${diskio_write /dev/nvme0n1} ${goto 12}: ${ioscheduler /dev/nvme0n1}
${fs_bar 10,10 /} ${fs_type /} ${fs_used /}/${fs_size /} ${fs_free_perc /}% ${fs_free /}
${top_io cpu 1}% ${goto 9}${top_io name 1} ${goto 22}${top_io pid 1} ${goto 32}
.
NET
${gw_iface}: ${addr enp42s0}/${gw_ip}
${totaldown enp42s0} ${totalup enp42s0} ${upspeed enp42s0} ${downspeed enp42s0}
.
REST
cpu temp k10temp:     ${hwmon k10temp temp 1} ${hwmon k10temp temp 3}
cpu temp nct6687:     ${hwmon nct6687 temp 1} ${hwmon nct6687 temp 2} ${hwmon nct6687 temp 3} ${hwmon nct6687 temp 4} ${hwmon nct6687 temp 5} ${hwmon nct6687 temp 6} ${hwmon nct6687 temp 7}
gpu temp:             ${hwmon nouveau temp 1} ${hwmon 1 temp 1}
ssd temp:             ${hwmon 0 temp 1} ${hwmon 0 temp 2} ${hwmon 0 temp 3}

${blink no?} ${scroll left 5 1 this the way to do it}
]]
