--[[
    # ? Mine Conky by allan_walpy [allanwalpy@gmail.com] and tested on Termux on android
]]

conky.config = {
    out_to_ncurses = false,
    out_to_console = true,
    out_to_x = false,
    out_to_wayland = false,

    console_graph_ticks = " ,▁,▂,▃,▄,▅,▆,▇,█",

    total_run_times = 0,

    forced_redraw = false,
    extra_newline = false,

    default_color = "#ffffff",
    color1 = "#88aaff",
    color2 = "#44ff88",
    color3 = "#ee6633",
    color4 = "#ff1111",
    color5 = "#44ff88",
    color6 = "#4488aa",
    color7 = "#33aa66",
    color8 = "#ff8844",
    color9 = "#ff1111",
    color0 = "#333333",
    default_outline_color = "#ffffff",
    default_shade_color = "#ffffff",

    update_interval = 1.25,
    cpu_avg_samples = 2,
    diskio_avg_samples = 2,
    net_avg_samples = 2,
    
    disable_auto_reload = false,

    text_buffer_size = 256,
    override_utf8_locale = true,
    no_buffers = true,
    if_up_strictness = "address",
    format_human_readable = true,
    short_units = false,
    pad_percents = 0,
    use_spacer = "none",
    temperature_unit = "celsius",
    
    default_graph_height = 32,
    default_graph_width = 127,
    default_gauge_height = 32,
    default_gauge_width = 127,
    
    top_name_verbose = false,
    top_name_width = 32,

--[[
    # templates
    # 0 - cpu bar;
    # 1 - process top;
    # 2 - mem top;
    $ 3 - disk info;
    # 4 - disk top;
]]

    template0 = "${cpugraph cpu\\1 1,25}${cpubar cpu\\1 1,20} ${freq_g \\1}Ghz ${cpu cpu\\1}%",
    template1 = "${top cpu \\1}% ${top name \\1} ${top pid \\1} ${top user \\1}",
    template2 = " ${top_mem mem_res \\1} ${top_mem name \\1} ${top_mem pid \\1} ${top_mem user \\1}",
    template3 = "\\2 ${fs_type \\1} ${fs_bar 1,20 \\1} ${fs_size \\1} [${fs_used \\1}/${fs_free \\1}]",
    template4 = "${top_io io_read \\1} ${top_io io_write \\1} ${top_io name \\1} ${top_io pid \\1} ${top_io user \\1}",
}

conky.text = [[
${no_update ${color5}${distribution}} ${exec cat /etc/debian_version} ${no_update ${machine} ${sysname} ${kernel}}
${no_update ${nodename}} ${time} [${uptime}]
${template0 0}
${loadavg 1}/${loadavg 2}/${loadavg 3} ${cpugovernor \\1}
${template0 1}
${template0 2}
${template0 3}
${template0 4}
${template0 5}
${template0 6}
${template0 7}
${template0 8}
${template0 9}
${template0 10}
${template0 11}
${template0 12}
${template1 1}
${template1 2}
${template1 3}
${template1 4}
${template1 5}
${template1 6}
${template1 7}
${template1 8}
${membar 1,33} ${swapbar 1,25}
${memmax}: ${mem}/${cached} ${memavail}  ${swapmax}: ${swap} ${swapfree}
${template2 1}
${template2 2}
${template2 3}
${template2 4}
${template2 5}
${template2 6}
${template2 7}
${template2 8}
${template3 / root___}
${template3 /media/walpy/private private}
${diskiograph_read 8,20 1000000}/${diskiograph_write 8,20 1000000} ▲${diskio_read /dev/nvme0n1} ▼${diskio_write /dev/nvme0n1}
${template4 1}
${template4 2}
${template4 3}
${template4 4}
${template4 5}
${template4 6}
${template4 7}
${template4 8}
${gw_iface}: ${addr enp42s0}/${gw_ip}
${upspeedgraph enp42s0 1,20 100000}/${downspeedgraph enp42s0 1,20 1000000} ▲${upspeed enp42s0} ▼${downspeed enp42s0}
cpu temp k10temp: ${hwmon k10temp temp 1} ${hwmon k10temp temp 3} nct6687: ${hwmon nct6687 temp 1} ${hwmon nct6687 temp 2} ${hwmon nct6687 temp 3} ${hwmon nct6687 temp 4} ${hwmon nct6687 temp 5} ${hwmon nct6687 temp 6} ${hwmon nct6687 temp 7}
ssd temp: ${hwmon 0 temp 1} ${hwmon 0 temp 2} ${hwmon 0 temp 3} gpu temp: ${hwmon nouveau temp 1} ${hwmon 1 temp 1}
███████████████████████████████████████████████████████████
███████████████████████████████████████████████████████████
FILE_FLASH
]]
