#!/bin/bash

[ $1 == "cpu" ] && cat /sys/class/hwmon/hwmon4/temp1_input | sed 's/.\{3\}$//'

[ $1 == "nvme" ] && cat /sys/class/hwmon/hwmon0/temp1_input | sed 's/.\{3\}$//'

[ $1 == "sata" ] && cat /sys/class/hwmon/hwmon2/temp1_input | sed 's/.\{3\}$//'

[ $1 == "drive" ] && (echo test) && (sudo smartctl -A /dev/$2 | grep -i temperature | awk  '{print $10}')
