#!/bin/bash

## this is auto start script
##  there must be a daemon in system to launch authostart;
##  you may create one with command `sudo nano /etc/systemd/system/{service-name}.service`
##  put following content in the file:
##   [Unit]
##   Description=Autostart bots on server
##   After=network.target
##
##   [Service]
##   Type=simple
##   WorkingDirectory=/home/{user}/script/
##   ExecStart=bash /home/{user}/script/autostart
##   Restart=no
##   KillSignal=SIGINT
##   SyslogIdentifier=script-autostart
##   User={user}
##
##   [Install]
##   WantedBy=multi-user.target
##
##  Replace `{user}` with your system username;
##  Enable service with command `sudo systemctl enable {service-name}.service`
##  Start service with command `sudo systemctl start {service-name}.service` to make sure it doing it's job;
##  You may check out status of service with command `sudo systemctl status {service-name}.service`

# runs music bot;
./run music

# runs twitchy bot;
./run twitchy