#!/bin/bash

# ? copy repository apt configuration to system folder `/etc/apt/` or other way around;

script_folder=$(dirname "$(readlink -fm "$0")")

sync_conf="-rltv"

system_folder_sources="/etc/apt/sources.list.d"
system_file_sources="/etc/apt/sources.list"
system_folder_preferences="/etc/apt/preferences.d"

repo_folder_sources=$script_folder"/sources"
repo_file_sources=$script_folder"/sources.list"
repo_folder_preferences=$script_folder"/preferences"


if [[ $1 == "pull" ]]; then
    echo " --- pulling apt configuration from system folder to repository --- "
    echo "     --- with \'$sync_conf\` args for rsync --- "

    rsync $sync_conf $system_folder_sources/* $repo_folder_sources
    rsync $sync_conf $system_file_sources $repo_file_sources

    rsync $sync_conf $system_folder_preferences/* $repo_folder_preferences

elif [[ $1 == "push" ]]; then
    echo " --- pushing apt configuration from repository to system folder --- "
    echo "     --- with \'$sync_conf\` args for rsync --- "

    sudo rsync $sync_conf $repo_folder_sources/* $system_folder_sources
    sudo rsync $sync_conf $repo_file_sources $system_file_sources

    sudo rsync $sync_conf $repo_folder_preferences/* $system_folder_preferences
  
else
    echo -e "\033[0;33m --- must specify action \`pull\` or \`push\` --- \033[0m"
    exit 1
fi

echo " --- done --- "
