#!/bin/bash

#++ installs clang, llvm, tools etc.
#++ arguments:
#++  - lang verison;

if [ $# -ne 1 ] ; then echo -e "\033[0;33m requires one argument: clang version \033[0m"; exit 1; fi

sudo update-alternatives --remove llvm-config /usr/bin/llvm-config-$1
sudo update-alternatives --remove clang /usr/bin/clang-$1
