#!/bin/bash

#++ installs nodejs etc.
#++ arguments:
#++  - nodejs verison;

if [ $# -ne 1 ] ; then echo -e "\033[0;33m requires one argument: nodejs version \033[0m"; exit 1; fi

script_directory=$(dirname "$(readlink -fm "$0")")
ubuntu_codename=$(lsb_release --codename --short)

$script_directory/../system/apt-key-add https://deb.nodesource.com/gpgkey/nodesource.gpg.key nodesource.gpg
echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$1.x $ubuntu_codename main
# deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$1.x $ubuntu_codename main
" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt update
sudo apt install nodejs
