#!/bin/bash

# ? creates audio sink for future audio rerouting; uses `pactl` util;
# ? arguments:
# ?  - sink name;

sink_name="$1-sink"

sink_info=$(pactl list short sinks | grep $sink_name)
if [ -z "$sink_info" ] ; then
    pactl load-module module-null-sink media.class=Audio/Sink sink_name=$sink_name channel_map=stereo
fi

pactl set-default-sink $sink_name