#!/bin/bash

# 1st argument - app name;
# 2nd argument [optional] [default=100] - number of lines shown

NAME=$1
COUNT=100

if [ ! -z "$2" ]; then
    COUNT=$2
fi;

tail -$COUNT ~/log/$NAME.log

exit 0