#!/bin/bash

#++ saves screenshot to `$HOME/Pictures/Screenshot/auto` folder and showing notification with process;
#++  - screenshot type, if specified have to contain either `full`, `window` or `region`; `full` on default or if specified incorrectly;

arg="-f"
postfix="fullscreen"
if [[ $# -ge 1 ]]; then
    if [[ $1 == "window" ]]; then
        arg="-w"
        postfix="window"
    fi
    if [[ $1 == "region" ]]; then
        arg="-r"
        postfix="region"
    fi
fi

timestamp=$(date +%F_%H-%M-%S_%N)
sub_folder=$(date +%Y_%m)

filename="$HOME/Pictures/Screenshots/$sub_folder/screenshot-$timestamp-$postfix.png"

command=""

xfce4-screenshooter $arg -s $filename && \
command=$(notify-send -u low -c im -a Screenshot -h string:desktop-entry:xfce4-screenshooter -t 5000 -i $filename -A "i"=image -A "f"=folder "screenshot" "... __:: success ::__ ...") || \
notify-send -u low -c im -a Screenshot -h string:desktop-entry:xfce4-screenshooter -t 10000 -i dialog-warning "screenshot" "... ::|| failure ||:: ..."

if [[ $command == "i" ]]; then
    shotwell $filename
fi

if [[ $command == "f" ]]; then
    nemo $filename
fi
