#!/bin/bash

# ? simple session manage; see "`script_name` help" to see available commands;

function get_confirmation {
    read -p " --- enter \`y\` to continue " choice
    case "$choice" in
        y|Y ) echo " --- proceeding";;
        * ) echo " -x- abort -x-"; exit 1;;
    esac
}

function do_systemctl_action {
    # ? 1 - command; 2 - name;
    echo " --- chosen: $2 ---"
    get_confirmation
    echo " --- executing \`sudo systemctl $1\`"
    #sudo systemctl $1
}

function do_sleep_soft {
    do_systemctl_action suspend "[sleep soft] --- suspend ---"
    return
}

function do_sleep_hard {
    do_systemctl_action hibernate "[sleep hard] --- hibernate ---"
    return
}

function do_sleep_mix {
    do_systemctl_action hybrid-sleep "[sleep mix] --- hybrid ---"
    return
}

function do_sleep_chain {
    do_systemctl_action suspend-then-hibernate "[sleep chain] --- slumber ---"
    return
}

function do_shut_reload {
    do_systemctl_action soft-reboot "[shut reload] --- reload ---"
    return
}

function do_shut_down {
    do_systemctl_action poweroff "[shut down] --- shutdown ---"
    return
}

function do_shut_reboot {
    do_systemctl_action reboot "[shut reboot] --- reboot ---"
    return
}

([[ "$*" == *"help"* ]] || [[ "$*" == *"man"* ]] || [[ "$*" == *"--help"* ]] || [[ "$*" == *"-h"* ]]) && \
echo " --- use \`script_name\` args; only one action permitted; only the first action in a following list will be executed;

    suspend - suspends session with \`systemctl suspend\`;
    aka: sus; sleep soft;

    hibernate - hibernate session with \`systemctl hibernate\`;
    aka: hib; sleep hard;

    hybrid - suspends and hibernates session at the same time with \`systemctl hybrid-sleep\`;
    aka: hyb; sleep mix; sleep both;

    slumber - suspends and later hibernates session with \`systemctl suspend-then-hibernate\`;
    aka: slum; slumb; sleep chain; sleep seq; sleep sequence; sleep bat; sleep battery;

    reload - reloads userspace without reloading machine with \`systemctl soft-reboot\`;
    aka: shut load;

    shutdown - shutdowns machine with \`systemctl poweroff\`;
    aka: shut down;

    reboot - reboots machine with \`systemctl reboot\`;
    aka: shut boot;

 ---" && exit 0

(([[ "$*" == *"sleep"* ]] && [[ "$*" == *"soft"* ]]) || [[ "$*" == *"suspend"* ]] || [[ "$*" == *"sus"* ]]) && do_sleep_soft

(([[ "$*" == *"sleep"* ]] && [[ "$*" == *"hard"* ]]) || [[ "$*" == *"hibernate"* ]] || [[ "$*" == *"hib"* ]]) && do_sleep_hard

(([[ "$*" == *"sleep"* ]] && ([[ "$*" == *"mix"* ]] || [[ "$*" == *"both"* ]])) || [[ "$*" == *"hybrid"* ]] || [[ "$*" == *"hyb"* ]]) && do_sleep_mix

(([[ "$*" == *"sleep"* ]] && ([[ "$*" == *"chain"* ]] || [[ "$*" == *"battery"* ]] || [[ "$*" == *"bat"* ]] || [[ "$*" == *"sequence"* ]] || [[ "$*" == *"seq"* ]])) || [[ "$*" == *"slumber"* ]] || [[ "$*" == *"slumb"* ]] || [[ "$*" == *"slum"* ]]) && do_sleep_chain

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"load"* ]]) || [[ "$*" == *"reload"* ]]) && do_shut_reload

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"down"* ]]) || [[ "$*" == *"shutdown"* ]]) && do_shut_down

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"boot"* ]]) || [[ "$*" == *"reboot"* ]]) && do_shut_reboot

echo " -x- command or action not found; see \"\`script_name\` help\" to see available actions; -x-"