#!/bin/bash

# ? simple session manage;
# ? args:
# ?     - `sleep`;
# ?         - [`suspend`] `soft`;
# ?     - `save`, `hibernate`

function get_confirmation {
    read -p " --- enter \`y\` to continue" choice
    case "$choice" in
        y|Y ) echo " --- proceeding";;
        * ) return 1;;
    esac
}

function do_systemctl_action {
    # ? 1 - command; 2 - name;
    echo " --- chosen: $2 ---"
    get_confirmation
    echo "sudo systemctl $1" #sudo systemctl $1
}

function do_sleep_soft {
    do_systemctl_action suspend "[sleep soft] --- suspend ---"
    return
}

function do_sleep_hard {
    do_systemctl_action hibernate "[sleep hard] --- hibernate ---"
    return
}

function do_sleep_mix {
    do_systemctl_action hybrid-sleep "[sleep mix] --- hybrid ---"
    return
}

function do_sleep_chain {
    do_systemctl_action suspend-then-hibernate "[sleep chain] --- slumber ---"
    return
}

function do_shut_reload {
    do_systemctl_action soft-reboot "[shut reload] --- reload ---"
    return
}

function do_shut_down {
    do_systemctl_action poweroff "[shut down] --- shutdown ---"
    return
}

function do_shut_reboot {
    do_systemctl_action reboot "[shut reboot] --- reboot ---"
    return
}

(([[ "$*" == *"sleep"* ]] && [[ "$*" == *"soft"* ]]) || [[ "$*" == *"suspend"* ]] || [[ "$*" == *"sus"* ]]) && do_sleep_soft

(([[ "$*" == *"sleep"* ]] && [[ "$*" == *"hard"* ]]) || [[ "$*" == *"hibernate"* ]] || [[ "$*" == *"hib"* ]]) && do_sleep_hard

(([[ "$*" == *"sleep"* ]] && ([[ "$*" == *"mix"* ]] || [[ "$*" == *"both"* ]])) || [[ "$*" == *"hybrid"* ]] || [[ "$*" == *"hyb"* ]]) && do_sleep_mix

(([[ "$*" == *"sleep"* ]] && ([[ "$*" == *"chain"* ]] || [[ "$*" == *"battery"* ]] || [[ "$*" == *"bat"* ]] || [[ "$*" == *"sequence"* ]] || [[ "$*" == *"seq"* ]])) || [[ "$*" == *"slumber"* ]] || [[ "$*" == *"slumb"* ]] || [[ "$*" == *"slum"* ]]) && do_sleep_chain

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"load"* ]]) || [[ "$*" == *"reload"* ]]) && do_shut_reload

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"down"* ]]) || [[ "$*" == *"shutdown"* ]]) && do_shut_down

(([[ "$*" == *"shut"* ]] && [[ "$*" == *"boot"* ]]) || [[ "$*" == *"reboot"* ]]) && do_shut_reboot
