#!/bin/bash

#++ manages apt packages, updates snap packages;
#++ - update ppa's and others;
#++ - update packages;
#++ - autoremove unused poackages;
#++ - remove resudential package configs;
#++ - [if installed] snap packages refresh;
#++ - [if installed] flatpak packages update;
#++ - [if installed] gnome-shell extensions update;

echo -e "\n\n --- update --  -- -- --- \n\n" && sudo apt update && \
echo -e "\n\n --- upgrade -- -- -- --- \n\n" && sudo apt upgrade && \
echo -e "\n\n --- full-upgrade  -- --- \n\n" && sudo apt full-upgrade && \
echo -e "\n\n --- auto-remove   -- --- \n\n" && sudo apt autoremove && \
echo -e "\n\n --- purge   -- -- -- --- \n\n" && sudo apt purge $(dpkg --get-selections | grep deinstall | cut -f1) && \
(command -v snap &> /dev/null && echo -e "\n\n --- snap -- -- -- -- --- \n\n" && sudo snap refresh || true) && \
(command -v flatpak &> /dev/null && echo -e "\n\n --- flatpak -- -- -- --- \n\n" && sudo flatpak update || true) && \
(command -v gnome-shell &> /dev/null && echo -e "\n\n --- gnome extensions --- \n\n" && \
    gdbus call --session --dest org.gnome.Shell.Extensions --object-path /org/gnome/Shell/Extensions \
        --method org.gnome.Shell.Extensions.CheckForUpdates || true) && \
[[ $1 != "--hide-done" ]] && echo -e "\n\n --- done -- -- -- -- --- \n\n" || true

#-- use `sudo apt -o APT::Get::Always-Include-Phased-Updates=true for disabling phased updates upgrade`;

#-- gnome-shell;
#-- see https://discourse.gnome.org/t/how-to-update-gnome-extensions-via-terminal/7531/2 for more info;
#-- for alternative way see gnome-shell updates see https://github.com/brunelli/gnome-shell-extension-installer ;
#-- for alternative way see https://pypi.org/project/gnome-extensions-cli/ ;
#-- restarting gnome-shell code;
#-- echo "Restarting GNOME Shell..."
#--   dbus-send --session --type=method_call \
#--            --dest=org.gnome.Shell /org/gnome/Shell \
#--             org.gnome.Shell.Eval string:"global.reexec_self();"
