#!/bin/bash

#++ manages apt packages, updates snap packages;
#++ - update ppa's and others;
#++ - update packages;
#++ - autoremove unused poackages;
#++ - remove resudential package configs;
#++ - [if installed] snap packages refresh;

echo -e "\n\n --- update --  -- -- --- \n\n" && sudo apt update && \
echo -e "\n\n --- upgrade -- -- -- --- \n\n" && sudo apt upgrade && \
echo -e "\n\n --- full-upgrade  -- --- \n\n" && sudo apt full-upgrade && \
echo -e "\n\n --- auto-remove   -- --- \n\n" && sudo apt autoremove && \
echo -e "\n\n --- purge   -- -- -- --- \n\n" && sudo apt purge $(dpkg --get-selections | grep deinstall | cut -f1) && \
(command -v snap &> /dev/null && echo -e "\n\n --- snap -- -- -- -- --- \n\n" && sudo snap refresh || true) && \
[[ $1 != "--hide-done" ]] && echo -e "\n\n --- done -- -- -- -- --- \n\n" || true
