#!/bin/bash

# ? link hub folder to `/home` user folder for easy use and hardcoded features;
# ? arguments:
# ?  - folder name to create in user home folder;

if [ $# -ne 1 ] ; then
    echo -e "\033[0;33m requires one argument: folder name to create in $HOME \033[0m"
    exit 1
fi

echo -e " - linking \"$(pwd)\" to \"$HOME/hub\"" && \
ln -s $(pwd) "$HOME/hub" && \
echo -e " - done"
