#!/bin/bash

maximum_update_interval=100000
current_update_interval=600

time_now=$(date +%s)

function get_filename() {
    echo ~/.cache/weather.$1.json
}

current_filename=$(get_filename current)
hourly_filename=$(get_filename hourly)
daily_filename=$(get_filename daily)

function get_file_age() {
    if [ ! -f $1 ]; then
        touch $1
        echo $maximum_update_interval
    else
        modification_time=$(date -r $1 +%s)
        echo $(($time_now - $modification_time))
    fi
}

function update_report() {
    ~/script/system/feature/conky/scripts/get_weather_report $1 $2
}

function update_on_need() {
    if [[ $(get_file_age $2) -ge $3 ]]; then
        echo $(update_report $1 $2)
    fi
}

function update_current_on_need() {
    echo $(update_on_need current $current_filename $current_update_interval)
}

function update_hourly_on_need() {
    minutes_since_hour=$(date +%M)
    max_age=$(($int($minutes_since_hour) * 60))
    echo $(update_on_need hourly $hourly_filename $max_age)
}

function update_daily_on_need() {
    hours_since_day=$(date +%H)
    max_age=$(($int($hours_since_day) * 60 * 60))
    echo $(update_on_need daily $daily_filename $max_age)
}

echo $(update_current_on_need)
echo $(update_hourly_on_need)
echo $(update_daily_on_need)
