#!/bin/bash

# ? copy `get_weather.example` to `get_weather.secret` and configure script;
# ? args
# ?  - section variable to pass in request
# ?  - filename for request output

function get_info() {
    ~/script/system/feature/conky/scripts/get_weather.secret $1
}

function get_request_uri() {
    echo "https://www.meteosource.com/api/v1/free/point?place_id=$3&sections=$1&language=en&units=metric&key=$2"
}

location=$(get_info "location")
key=$(get_info "key")

uri=$(get_request_uri $1 $key $location)

curl -X 'GET' $uri -H 'accept: application/json' -s -o $2
