#!/bin/bash

# ? args
# ?  - type [current, hourly, daily]
# ?  - path to setting
# ?  - [optional] post processing command


filename=~/.cache/weather.$1.json

result=$(cat $filename | jq -r .$1.$2)

if [[ $3 == *"int"* ]]; then
   result=$(echo $result | awk '{print int($1)}')
fi

echo $result
