#!/bin/bash

#++ connect/disconnect/reconnect to/from/the vpn;

if [[ $# < 1 ]]; then
    echo -e "\033[0;33m requires one argument: connect/disconnect/reconnect command\033[0m"
    exit 1
fi

if [[ $1 == "connect" || $1 == "c" || $1 == "on" ]]; then
    if [ $# -ne 2 ]; then
        echo -e "\033[0;33m connect command requires additional argument: country letter code\033[0m"
        exit 1
    fi
    echo " --- connect ---"
    protonvpn-cli connect --cc $2 --protocol tcp
    exit 0
fi

if [[ $1 == "disconnect" || $1 == "d" || $1 == "off" ]]; then
    protonvpn-cli disconnect
    exit 0
fi

if [[ $1 == "reconnect" || $1 == "r" || $1 == "restart" || $1 == "re" ]]; then
    protonvpn-cli reconnect
    exit 0
fi

echo -e "\033[0;33m unrecognized command\033[0m"
exit 128
